### ISSUE TITLE
Simplify protocol/sketch configuration for Measurement

### ISSUE THREAD

**Issue by SanjayVas** [world-federation-of-advertisers/cross-media-measurement-api#11]
Currently, `MeasurementSpec` contains a `SketchConfig`. This is a very flexible configuration used by the `AnySketch` library. The CMMS API need not expose this level of flexibility for Measurement creation, and can instead have a minimal protocol-specific configuration that can be used to generate a `SketchConfig`. Additionally, there are some parameters that can be specified per-Measurement such as those related to differential privacy.

The basic idea is that the MC can specify the measurement type (e.g. "reach and frequency") and the params for that type (e.g. epsilons for differential privacy). The CMMS selects the appropriate protocol for that measurement type (e.g. Liquid Legions v2) and the appropriate well-known configuration for that protocol (e.g. the decay rate and size of a Liquid Legions sketch). It can use these to generate a `SketchConfig`.

API changes:
* Replace `SketchConfig` in `MeasurementSpec` with a oneof to specify the measurement type and its params.
* Have a resource type that exposes a well-known set of protocol configurations provided by the CMMS. This would replace the `SketchConfig` resource type.
* Include the well-known protocol config resource key and resulting `SketchConfig` in each Requisition.

**Comment by SanjayVas** [comment]
This is related to world-federation-of-advertisers/cross-media-measurement/pull/17.

**Comment by wangyaopw** [comment]
LGTM

**Comment by kungfucraig** [comment]
LGTM

**Comment by SanjayVas** [comment]
Per @wangyaopw's comment in #13, the protocol-specific params can be used to deterministically generate an AnySketch `SketchConfig`. Therefore, we need not generate an API `SketchConfig` message just to have EDP clients convert that to an AnySketch `SketchConfig`.
